id: I3A30D9C8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:41:18+00:00'
last_modified: '2022-06-08T11:38:35.765539+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W26097
  title: རྒྱལ་དབང་ལྔ་པ་ཆེན་པོའི་རྣམ་ཐར་དོན་བསྡུས་རབ་སྙན་གཞན་གསོས་ཀྱི་གླུ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CA4D:
      image_group_id: I1CZ2704
      title: ''
      total_pages: 366
      order: 1
      base_file: CA4D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
