id: P009524
initial_creation_type: ocr
source_metadata:
  id: bdr:W26097
  title: རྒྱལ་དབང་ལྔ་པ་ཆེན་པོའི་རྣམ་ཐར་དོན་བསྡུས་རབ་སྙན་གཞན་གསོས་ཀྱི་གླུ
  author: ''
  volumes:
    5f3528c3bc2c4d07812f75b039b99069:
      image_group_id: I1CZ2704
      title: ''
      volume_number: 1
      total_pages: 366
      base_file: v001.txt
