id: P009524
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:36:22.105168
source_metadata:
  id: bdr:W26097
  title: རྒྱལ་དབང་ལྔ་པ་ཆེན་པོའི་རྣམ་ཐར་དོན་བསྡུས་རབ་སྙན་གཞན་གསོས་ཀྱི་གླུ
  author: ''
  volumes:
    5f3528c3bc2c4d07812f75b039b99069:
      image_group_id: I1CZ2704
      title: ''
      volume_number: 1
      total_pages: 366
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
